### ISSUE TITLE
Can you add the ability to remap to mojang names as intermediaries 

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/tiny-remapper#105]
This would allow mods to use mojang names like forge does plus it could allow fabric api to be possibly work along side forge or the other way round

**Comment by modmuss50** [comment]
Tiny remapper already supports Mojang's (proguard) mappings by using the mapping-io library.

> This would allow mods to use mojang names like forge does 

This has been possible for years.

> plus it could allow fabric api to be possibly work along side forge or the other way round

No it couldn't
