### ISSUE TITLE
Methods and fields are not remapped

### ISSUE THREAD

**Issue by geckwwo** [FabricMC/tiny-remapper#119]
For some reason, methods and fields are not remapped in my JAR, even though classes are.
![Remapped (partially)](https://github.com/FabricMC/tiny-remapper/assets/59973962/ef9d1a7b-e9a5-4bb0-8a21-979010d20543)
![Original](https://github.com/FabricMC/tiny-remapper/assets/59973962/eb97583f-6f7b-4ca8-8057-6942e0d9a905)
![Mappings](https://github.com/FabricMC/tiny-remapper/assets/59973962/5adce83e-2abd-400c-bf1a-6cc80c767913)
![Folder with all the stuff](https://github.com/FabricMC/tiny-remapper/assets/59973962/20336e4b-2e43-494e-ae27-457d221b31ea)
Command line:
```
java -jar tiny-remapper-0.8.9-fat.jar cursedqol-premapped.jar cursedqol.jar rbt20231029.tiny named intermediary client.jar
```
Output:
```
Finished after 560,64 ms.
```
(client.jar is the JAR where the obfuscated classes and stuff are defined, but I'm remapping other jar, not related to this one, other than with mappings)

**Comment by modmuss50** [comment]
Is client.jar remapped to `named`? It must be in the same namespace as the jar you are remapping.

**Comment by geckwwo** [comment]
Yep, did all that, now it's remapped. Same namespace thing is really weird, but eh, whatever
