### ISSUE TITLE
Update ASM to 9.7 to support Java 23

### ISSUE THREAD

**Issue by mpfaff** [FabricMC/tiny-remapper#129]
The current version, 9.6, does not support Java 23 class-files.

**Comment by modmuss50** [comment]
Hi, we are waiting on 9.8 (or whatever the next version is) with a fix for: https://gitlab.ow2.org/asm/asm/-/issues/318014

You should be able to update to 9.7 on your own if you need this sooner.

**Comment by mpfaff** [comment]
Ah, that's fair. I was able to override the version to 9.7 for my project like you suggested. You can go ahead and close the issue, or keep it until 9.8 is released. Up to you.

**Comment by modmuss50** [comment]
Thats great, ill likely close this as usually there is little rush for us to update to the bleeding edge versions, and like you said its easy enough to override in your project 👍
