### ISSUE TITLE
FAILED TO LOAD OPTIFINE

### ISSUE THREAD

**Issue by OsitoUwU123** [FabricMC/tiny-remapper#131]
**my optifabric is not working says:**

**Failed to load optifine,please report this**

**net/fabricmc/tinyremapper/IMapingProvider**

**if you can help me, I would appreciate it, I need this.**

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
