### ISSUE TITLE
Parameters of overriding methods are not remapped

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/tiny-remapper#18]
@liach

**Comment by ramidzkh** [comment]
Tinyv2:tm:

**Comment by liach** [comment]
Did it work before #15 was merged

**Comment by natanfudge** [comment]
No idea, I can use an older version, which one doesn't have that?

**Comment by natanfudge** [comment]
It does not work in `0.2.0.43` (before #15 ) either.

**Comment by natanfudge** [comment]
Good news
I don't know what I did but it works now

**Comment by natanfudge** [comment]
Oh I do know - the mappings of overriding methods are included in the tiny files now.
