### ISSUE TITLE
How do I use this to remap from intermediate to human friendly mappings by hand?

### ISSUE THREAD

**Issue by alxpettit** [FabricMC/tiny-remapper#41]
I'd like to remap a mod with a Fabric mod with a fairly libre license but that has no source code release. How would I do this with tiny-remapper?

**Comment by i509VCB** [comment]
I do really feel we need some more documentation for TR ~~looks at @sfPlayer1~~.

You could probably use the CLI to remap the mod. Simply you need two things: an `intermediary -> yarn/mojmap` mapping file. You can grab this from loom from gradle's caches. For me those are located at `/home/i509vcb/.gradle/caches/modules-2/files-2.1/net.fabricmc/yarn/1.16.3+build.47/132545b943d86dd59551fe7e18163f14230e547c/`

If you extract the jar, you'll get a `./tiny` file suitable for the job.

The basic usage of TR is as follows:
```
usage: <input> <output> <mappings> <from> <to> [<classpath>]... [--reverse] [--forcePropagation=<file>] [--propagatePrivate] [--ignoreConflicts]
```

Next you will get yourself a tiny remapper build and run this command most likely:
`java -jar tiny-remapper-blah.jar` intermediarymod.jar remappedjar.jar intermediary named`

The classpath would be a link to jar files such as dependencies (such as CCA if the mod depends on that). I highly reccomend feeding in an intermediary mapped Minecraft jar for the best remap possible. Also possible to obtain in gradle caches (can't remember off head).

I do believe player wants to add a simple swing gui to tiny remapper so things aren't as command heavy.

Hopefully this helps you out, if you don't understand something I'll see if I can get player to explain it any better :)

**Comment by alxpettit** [comment]
I for one _love_ command lines, but I can understand if not everyone shares my fetish.

**Comment by alxpettit** [comment]
I'm getting:
```
$ tiny-remapper Allure-1.2.7.jar Allure-1.2.7-remapped-1.16.3.jar yarn-1.16.3+build.17-v2.tiny intermediary named
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor
	at net.fabricmc.tinyremapper.Main.main(Main.java:175)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

**Comment by i509VCB** [comment]
Did you grab the `-all` distribution of tiny remapper? That is available on maven

**Comment by alxpettit** [comment]
No, I just compiled a jar from git repo. :S

**Comment by i509VCB** [comment]
Buildscript says there should be a fatjar that was built?

**Comment by alxpettit** [comment]
Yes, I see a `tiny-remapper-0.3.1-fat.jar` under `build/libs`.

**Comment by alxpettit** [comment]
Yay, it worked! Thank you :)
