### ISSUE TITLE
Multi-release JARs break when remapping

### ISSUE THREAD

**Issue by ramidzkh** [FabricMC/tiny-remapper#45]
1. Inspect App.jar. Notice that there are files with the same name as `App` within the `META-INF/versions` folder
2. Try running `App.jar App2.jar mappings.tiny a b`
3. The remapper complains several times
```
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
duplicate input class App, from App.jar and App.jar
Finished after 398.13 ms.
```
4. Inspect the remapped jar. Notice that the classes inside `META-INF/versions` is now missing. The multi-release jar is now broken

(These files are free from copyright) [Files.zip](https://github.com/FabricMC/tiny-remapper/files/5871100/Files.zip)

**Comment by sfPlayer1** [comment]
This is a problem with TR not supporting multi-release jars at this moment. It isn't super trivial to implement since it involves semi-independent classes with the same name that may use a completely different sub graph in the class hierarchy.

**Comment by gudenau** [comment]
Couldn't you do this in passes?

Get the highest version view of the jar and have everything lower be read-only, do the next highest one, etc..

Seems like the simplest way to handle this.

**Comment by gudenau** [comment]
I think I have come up with a version of Tiny Remapper that works MRJs, I will throw a few tests cases at it tomorrow and if it passes those I'll make a PR for it.

**Comment by LogicFan** [comment]
Hi, is there anyone working on this? If not, I can have a try.

**Comment by sfPlayer1** [comment]
It is quite high on the TODO list, not working on it yet though. Not sure about the best approach, might be easiest to create a completely separate model for each version, otherwise everything needs to become aware of multiple same-id class instances with their own parent/child relationships.

**Comment by LogicFan** [comment]
This is finished in the `remapbridges` branch.
