### ISSUE TITLE
Asm remapper update for constants

### ISSUE THREAD

**Issue by liach** [FabricMC/tiny-remapper#51]
Now Minecraft is on java 16, and java has way more builtin bootstrap methods. There is object methods for records, string concatenate factory for java 9+ string, methodhandles lookup classdata, also all constantsbootstraps methods.

We are currently just pumping errors for unknown indys: https://github.com/FabricMC/tiny-remapper/blob/a03a36293a876bf0b8e0756c2b6a1d14c7eddb1f/src/main/java/net/fabricmc/tinyremapper/AsmClassRemapper.java#L198

when using yarn for new minecraft, it is currently pumping tons of string concatenation indy messages.

Also, the remapper should be ready to handle condy (dynamic constants).

**Comment by liach** [comment]
On a side note, 28f6f28f112582931e0506212e089c7e4f05e536 handles string concat (on an off branch). Still preferable to handle things like hidden class bootstrap dark magic, etc.

**Comment by LambdAurora** [comment]
Any update on this issue?

It's been a while now and it's really starting to get old.

**Comment by liach** [comment]
Most updates now are happening on https://github.com/FabricMC/tiny-remapper/tree/remapbridges fyi

**Comment by sfPlayer1** [comment]
This was already fixed in https://github.com/FabricMC/tiny-remapper/commit/28f6f28f112582931e0506212e089c7e4f05e536 - merge and release pending shortly
