### ISSUE TITLE
The current `extraAnalyzeVisitor` API is hard to use.

### ISSUE THREAD

**Issue by LogicFan** [FabricMC/tiny-remapper#64]
Because of the way that the API is designed, there is a single `ClassVisitor` instance for processing all classes. Additionally, notice that this `ClassVisitor` is called in a concurrent environment, which makes the thing worse. In order to pass the value across `@Override` methods (e.g. `visit***`), the only way is to use a thread-local variable and remove it at the `visitEnd`. This is way too hacky and easy for developers to mess up.

Thus, I propose to have an overload of `extraAnalyzeVisitor` that takes function wrapper similar to #62 that creats `ClassVisitor` on the fly. 

To maintain backward compatibility, the old method that takes a `ClassVisitor` will still exists, and will simply be
```Java
public Builder extraAnalyzeVisitor(Supplier<ClassVisitor> func) {
	extraAnalyzeVisitor = func;
	return this;
}

public Builder extraAnalyzeVisitor(ClassVisitor visitor) {
	return extraAnalyzeVisitor(() -> visitor);
}
```

**Comment by Devan-Kerman** [comment]
I don't think backwards compatibility is a priority for TR, but this is kinda minor so meh

**Comment by LogicFan** [comment]
Close by f00529c170cbadbe343854bc8c1552f0fb57a759
