### ISSUE TITLE
Non .class resources are not copied to remapped Jar

### ISSUE THREAD

**Issue by NZSmartie** [FabricMC/tiny-remapper#8]
Tiny-Remapper only remaps class resources from a source jar to the output jar, while not touching any of the other resources such as `META-INF\MANIFEST.MF`
https://github.com/FabricMC/tiny-remapper/blob/b0d3ece1084522eb895f1edbdf37c9f11eee734e/src/main/java/net/fabricmc/tinyremapper/TinyRemapper.java#L410-L427

This affects fabrtic-loader 0.4 with the class loader no longer being preloaded with external classpaths. Only the remapped jar is proposed which is lacking a manifest 

Related: https://github.com/FabricMC/fabric-loader/pull/84

**Comment by sfPlayer1** [comment]
OutputConsumerPath.addNonClassFiles handles copying non-class files, I've just extended it to take care of common META-INF artefacts.
