### ISSUE TITLE
Document Tiny Formats

### ISSUE THREAD

**Issue by gudenau** [FabricMC/tiny-remapper#83]
Would it be possible to more formally document the format that Tiny Remapper expects? It would beat reading the code and would be helpful for creating more tools that understand the formats.

**Comment by sfPlayer1** [comment]
https://github.com/FabricMC/tiny-remapper/issues/9

**Comment by gudenau** [comment]
Is there one for v1 as well?

I also meant more like a wiki page on this repo.

**Comment by NebelNidas** [comment]
Can be closed now, the spec is here: https://fabricmc.net/wiki/documentation:tiny
